# Generated by Django 4.2.7 on 2025-09-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('min_quantity', models.PositiveIntegerField(default=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sweet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='sweets.sweet')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
